# Numerical Python - Numpy

In [ ]:
import numpy as np

print("olá")

olá


## Trabalhando com Python Numpy

In [3]:
notas_alunos = ["Fernando", "Luan", "Lucas", "Pedro", "Anna Julia", "Farias", "Caio"]
notas_alunos = [5,6,4,10,9,8,10]

# Convertendo essas notas de 0 até 10 para 0 até 4
# print(notas_alunos/10 * 4) - Python puro não funciona
# print(otas_notas/10.0 * 4.0) - Python puro não funciona

for nota in notas_alunos:
    print(nota / 10 * 4)

# Mostrar somente as notas pares;
for nota in notas_alunos:
    if nota % 2 == 0:
        print("par",nota)

2.0
2.4
1.6
4.0
3.6
3.2
4.0
par 6
par 4
par 10
par 8
par 10


In [4]:
rng = np.random.default_rng(12345)
notas_aleatorias = rng.integers(low=0, high=10, size=10_000_000)


notas_aleatorias_lista = list(notas_aleatorias) #10_000_000 notas aleatórias


# for nota in notas_aleatorias_lista:
#     print(nota / 10 * 4)


notas_aleatorias / 10 * 4 # 100x mais rápido do que Python puro.

array([2.4, 0.8, 2.8, ..., 2.4, 1.2, 0.8], shape=(10000000,))

In [7]:
# Como Criar um array Numpy? array

array_notas = np.array([7,8,9,10])

# Operações vetorizados - ADEUS E WHILE!
print(array_notas + 10)
print((array_notas * 10 / 3 + 5) * 2)

[17 18 19 20]
[56.66666667 63.33333333 70.         76.66666667]


In [ ]:
print(array_notas)
print(array_notas > 8)
# Filtragem -> Máscara de Valores
print(array_notas[array_notas > 8])

[ 7  8  9 10]
[False False  True  True]
[ 9 10]


In [ ]:
np.sum() 
np.mean()
max()
min()
np.size() 

In [ ]:
print(max(array_notas))
print(min(array_notas))
print(np.sum(array_notas))
print(np.mean(array_notas))
print(np.size)